ENV['VAGRANT_EXPERIMENTAL'] = 'typed_triggers'

VM_CPUS = 2
VM_MEMORY = 2*1024 # MB
VM_DISK = 64 # GB

require 'open3'

Vagrant.configure(2) do |config|
  config.vm.box = 'fedora-44-amd64'

  config.vm.provider 'libvirt' do |lv, config|
    lv.memory = VM_MEMORY
    lv.cpus = VM_CPUS
    lv.cpu_mode = 'host-passthrough'
    lv.nested = true
    lv.keymap = 'pt'
    lv.machine_virtual_size = VM_DISK # GB
    lv.disk_driver :discard => 'unmap', :cache => 'unsafe'
    config.vm.synced_folder '.', '/vagrant', type: 'nfs', nfs_version: '4.2', nfs_udp: false
  end

  config.vm.provider 'vsphere' do |vsphere, config|
    vsphere.name = ENV['VSPHERE_VM_NAME']
    vsphere.notes = "Created from #{__FILE__}"
    vsphere.cpu_count = VM_CPUS
    vsphere.memory_mb = VM_MEMORY
    vsphere.user = ENV['GOVC_USERNAME']
    vsphere.password = ENV['GOVC_PASSWORD']
    vsphere.insecure = true
    vsphere.host = ENV['GOVC_HOST']
    vsphere.data_center_name = ENV['GOVC_DATACENTER']
    vsphere.compute_resource_name = ENV['GOVC_CLUSTER']
    vsphere.data_store_name = ENV['GOVC_DATASTORE']
    vsphere.template_name = ENV['VSPHERE_TEMPLATE_NAME']
    vsphere.vm_base_path = ENV['VSPHERE_VM_FOLDER']
    vsphere.vlan = ENV['VSPHERE_VLAN']
    if ENV['VAGRANT_SMB_PASSWORD']
      config.vm.synced_folder '.', '/vagrant',
        type: 'smb',
        smb_username: ENV['VAGRANT_SMB_USERNAME'] || ENV['USER'],
        smb_password: ENV['VAGRANT_SMB_PASSWORD']
    end
    config.trigger.after :'VagrantPlugins::VSphere::Action::Clone', type: :action do |trigger|
      trigger.info = 'Setting the disk size...'
      trigger.ruby do |env, machine|
        stdout, stderr, status = Open3.capture3(
          'govc',
          'vm.disk.change',
          '-vm.uuid', machine.id,
          '-disk.name', 'disk-1000-0',
          '-size', "#{VM_DISK}GB")
        if status.exitstatus != 0
          raise "failed to set the disk size. status=#{status.exitstatus} stdout=#{stdout} stderr=#{stderr}"
        end
      end
    end
  end

  config.vm.provision 'shell', name: 'Resize Disk', path: 'provision-resize-disk.sh'
  config.vm.provision 'shell', inline: 'cat /etc/os-release'
  config.vm.provision 'shell', inline: 'uname -a'
  config.vm.provision 'shell', inline: 'echo "machine-id is $(cat /etc/machine-id)"'
  config.vm.provision 'shell', inline: 'lsblk -o KNAME,SIZE,TRAN,FSTYPE,UUID,LABEL,MODEL,SERIAL'
  config.vm.provision 'shell', inline: 'df -h'
end
